# Generated by Django 3.0.1 on 2020-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score1',
            field=models.FloatField(null=True, verbose_name='Score 1'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score2',
            field=models.FloatField(null=True, verbose_name='Score 2'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='systemscore',
            field=models.FloatField(null=True, verbose_name='System score'),
        ),
    ]
