# Generated by Django 3.0.1 on 2020-02-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0002_auto_20200113_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('value', models.FloatField(verbose_name='Value')),
            ],
        ),
    ]
