# Generated by Django 3.0.1 on 2020-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorer', '0004_student_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='systemclass',
            field=models.IntegerField(null=True, verbose_name='Score class'),
        ),
    ]
